version: '3'

services:
  psql:
    build:
      context: ./docker/psql
      dockerfile: Dockerfile
    image: psql
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
      - ./docker/psql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=go_pg
      - TZ=Asia/Tokyo

  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  psql_data:
    driver: local