version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=go_pg
      - TZ=Asia/Tokyo
  test_db:
    image: postgres:latest
    container_name: postgres_test
    ports:
      - "25432:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go_pg_test
      - TZ=Asia/Tokyo

  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
