// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTest struct {
	Name string `json:"name"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Test struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateTest struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateUserInput struct {
	ID       int     `json:"id"`
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}

type User struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
