// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangePasswordInput struct {
	ID          int    `json:"id"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Password string `json:"password"`
}

type CreateTaskInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	DueDate     *string `json:"dueDate"`
	UserID      *int    `json:"user_id"`
	Status      string  `json:"status"`
}

type CreateTest struct {
	Name string `json:"name"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ListProductInput struct {
	Name          *string `json:"name"`
	Price         *uint32 `json:"price"`
	DiscountPrice *uint32 `json:"discountPrice"`
	Status        *string `json:"status"`
	UserID        *uint32 `json:"userId"`
	CreatedAtFrom *string `json:"createdAtFrom"`
	CreatedAtTo   *string `json:"createdAtTo"`
}

type ListTaskInput struct {
	Title     *string `json:"title"`
	Completed *bool   `json:"completed"`
	UserID    *uint32 `json:"user_id"`
	Status    *string `json:"status"`
}

type Product struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	Price         uint32  `json:"price"`
	DiscountPrice *uint32 `json:"discountPrice"`
	Status        string  `json:"status"`
	UserID        uint32  `json:"user_id"`
	CreatedAt     string  `json:"createdAt"`
	UpdatedAt     string  `json:"updatedAt"`
}

type Task struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	DueDate     string `json:"dueDate"`
	Completed   bool   `json:"completed"`
	UserID      int    `json:"user_id"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Test struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateTest struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateUserInput struct {
	ID       int     `json:"id"`
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}

type User struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
