// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTest struct {
	Name string `json:"name"`
}

type Test struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateTest struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
